### ISSUE TITLE
st.experimental_set_query_params warning

### ISSUE THREAD

**Issue by nara3m** [pop-srw/streamlit-cognito-auth#19]
Many thanks for the super useful package. I am sure contributors are aware of below warning. I would like to bring to your attention anyway:

`auth.py` uses `st.experimental_set_query_params` which will be removed after 2024-04-11. Warning message refers to it's replacement `st.query_params`. [see docs](https://docs.streamlit.io/library/api-reference/utilities/st.query_params) for more information.

The following changes will fix the issue

replace line 654 with 
`code = st.query_params["code"]`

& line 663 with
`st.query_params.clear()
`

then, lines 638-644, 652-653 can be deleted

**Comment by pop-srw** [comment]
I've updated to use the new query param variable in PR #10
